spring.application.name=sameera_rice_backend
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/sameera_rice_db
spring.datasource.username=sameera_user
spring.datasource.password=Dulan@25467
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Email Configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sewmininilakshi919@gmail.com
spring.mail.password=awbwftdtkhkapauz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
